### ISSUE TITLE
Atmega2561 freezing after burning (TFTP)

### ISSUE THREAD

**Issue by janioanselmo** [OpenEscapeControl/AVR-Etherboot#1]
Hello, I'm having a problem after TFTP file transfer (.hex).
When I make simple firmware recordings, such as "blink" (size = <5kB), I succeed! However, when I transfer (by TFTP) my complete code (size = 110kB) the Atmega freezes, does not initialize / freeze. What happens is when I use the USB recorder (USBasp) everything happens normally, successfully! That is, I have problems with TFTP (AVR-Bootloader). I do not find anything about, or similar questions around here. I will leave some information that may be relevant:

makefile.in:
MCU = atmega2561
EMB_FLASHEND = 0x3FFFF
EMB_BOOTLOADER_SECTION_START = 0x3FC00
EMB_LINKER_SCRIPT = -T ../make.files/eth-avr6.x
F_CPU = 16000000
EMB_BOOTLOADER_FLAVOR = 1

size.txt:
device_002.sizeelf:
section size addr
.data 0x0 0x800200
.text 0x34a 0x3fc00
.bootloader 0xe3c 0x0
.bss 0x30f 0x800200
.eeprom 0x72 0x810000
.comment 0x11 0x0
.note.gnu.avr.deviceinfo 0x40 0x0
.debug_aranges 0x1e8 0x0
.debug_info 0x2ece 0x0
.debug_abbrev 0x1678 0x0
.debug_line 0x10a3 0x0
.debug_frame 0x4c8 0x0
.debug_str 0xc7b 0x0
.debug_loc 0x11dc 0x0
.debug_ranges 0x148 0x0
Total 0x9190

BL_CODE_START 0x3EDC4

Note:
1) When, I am reducing / deleting the internal functions of my "complete code (110kB)" it initializes, however it hangs / freezes in other functions. Completely unstable;
2) I am using Arduino IDE 1.8.5 and the code is: 15% ROM and 37% RAM, with size of 110kB;
3) Card package: https://github.com/MCUdude/MegaCore
4) USBasp Recorder

**Comment by sergeivolodin** [comment]
@janioanselmo , can you try to record a network dump using wireshark/tcpdump? I think that first step would be to see if the firmware has finished loading to the device (Arduino sends a confirmation to the PC after each packed, including the final one)

**Comment by janioanselmo** [comment]
Hello, @sergeivolodin 
First, thank you for your consideration! It is very gratifying for me to receive technical aid! Actually I'm very happy, because I believe that in other discussions (github), today, we find the solution! I'll post here!
Again, thanks for the concern!

**Comment by janioanselmo** [comment]
The solution: https://github.com/cniweb/avr-etherboot/issues/7
Credits for:  https://github.com/hubsif & https://github.com/cniweb
Thanks!
